import { TranslationMap } from './types';

export const TRANSLATIONS: TranslationMap = {
  en: {
    dashboard: 'Dashboard',
    sales: 'Sales',
    delivery: 'Delivery',
    marketing: 'Marketing',
    purchase: 'Purchase',
    expenses: 'Expenses',
    stock: 'Inventory',
    parties: 'Parties',
    reports: 'Reports',
    settings: 'Settings',
    home: 'Home',
    promo_sms: 'Promo & SMS',
    courier: 'Courier',
    inventory: 'Inventory',
    todays_overview: "Today's Overview",
    total_sales: "Total Sales",
    total_expense: "Total Expense",
    net_profit: "Net Profit",
    pending_delivery: "Pending Delivery",
    new_sale: "New Sale",
    bulk_sms: "Bulk SMS",
    search_product: "Search Product...",
    bill: "Bill",
    items: "Items",
    total: "Total",
    checkout: "Checkout",
    finalize_sale: "Finalize Sale",
    customer: "Customer",
    walk_in: "Walk-in Customer",
    coupon_code: "Coupon Code",
    apply: "Apply",
    store_pickup: "Store Pickup",
    courier_delivery: "Courier Delivery",
    payment_method: "Payment Method",
    subtotal: "Subtotal",
    discount: "Discount",
    delivery_fee: "Delivery Fee",
    total_payable: "Total Payable",
    paid_amount: "Paid Amount",
    due: "Due",
    confirm_sale: "Confirm Sale",
    delivery_tracking: "Delivery Tracking",
    order_id: "Order ID",
    tracking: "Tracking",
    status: "Status",
    coupon_management: "Coupon Management",
    bulk_sms_marketing: "Bulk SMS Marketing",
    send_broadcast: "Send Broadcast",
    sales_report_invoice: "Sales Report & Invoice",
    date: "Date",
    amount: "Amount",
    method: "Method",
    action: "Action",
    invoice: "Invoice",
    add_expense: "Add Expense",
    note: "Note",
    category: "Category",
    product_stock: "Product Stock",
    add_product: "Add Product",
    name: "Name",
    cost: "Costing Price",
    price: "MRP",
    party_list: "Party List",
    add_party: "Add Party",
    suppliers: "Suppliers",
    purchase_stock: "Purchase Stock",
    supplier: "Supplier",
    product: "Product",
    qty: "Qty",
    unit_cost: "Unit Cost",
    confirm_purchase: "Confirm Purchase",
    shop_config: "Shop Configuration",
    shop_name: "Shop Name",
    currency: "Currency",
    save_changes: "Save Changes",
    log_out: "Log Out",
    owner: "Owner",
    business_suite: "Business Suite",
    pending: "Pending",
    shipped: "Shipped",
    delivered: "Delivered",
    type_message: "Type your message here...",
    add: "Add",
    close: "Close",
    print_invoice: "Print Invoice",
    bill_to: "Bill To",
    via: "Via",
    history: "History",
    stock_log: "Stock Log",
    low_stock: "Low Stock",
    adjustment: "Adjustment",
    purchase_history: "Purchase History",
    total_spent: "Total Spent",
    view_history: "View History",
    inv_dashboard: "Inventory Dashboard",
    product_list: "Product List",
    stock_report: "Stock Report",
    detailed_report: "Detailed Report",
    stock_ledger: "Stock Ledger",
    stock_transfer: "Stock Transfer",
    serial_manage: "Serial Manager",
    total_items: "Total Items",
    stock_value_cost: "Stock Value (Cost)",
    stock_value_sales: "Stock Value (Sales)",
    est_profit: "Est. Profit",
    transfer: "Transfer",
    from: "From",
    to: "To",
    serial_no: "Serial No",
    add_serial: "Add Serial",
    available: "Available",
    sold: "Sold",
    brand: "Brand",
    units: "Units",
    size: "Size",
    color: "Color",
    wholesale_price: "Wholesale Price",
    vat: "VAT",
    is_vat: "Is Vat Applicable?",
    alert_qty: "Stock Alert Quantity",
    stock_in: "Stock In",
    warranty: "Warranty",
    mfg_date: "Manufacturing Date",
    exp_date: "Expiry Date",
    upload_photo: "Upload Photo",
    variations: "Variations",
    sku: "SKU",
    create_invoice: "Create Invoice",
    sold_history: "Sold History",
    sold_products: "Sold Products",
    customer_history: "Customer History",
    retail_sale: "Retail Sale",
    wholesale: "Wholesale",
    phone_number: "Phone Number",
    customer_name: "Customer Name",
    address: "Address",
    total_qty: "Total Qty",
    additional_expense: "Additional Expense",
    total_discount: "Total Discount",
    change_amount: "Change Amount",
    remarks: "Remarks",
    service_staff: "Service Staff",
    sl: "SL",
    invoice_no: "Invoice No",
    type: "Type",
    quantity: "Quantity",
    store_name: "Store Name",
    faq: "FAQ",
    help: "Help",
    faq_title: "Frequently Asked Questions",
    faq_subtitle: "Find answers to commonly asked questions",
    q1: "How can I reset my password?",
    q2: "Do you offer a free trial?",
    q3: "Can I change my subscription plan later?",
    q4: "Is my data secure?",
    q5: "Do you provide customer support?",
    support: "Help & Support",
    ticket_list: "Ticket List",
    create_ticket: "Create Ticket",
    hotline: "Hotline",
    submit_ticket: "Submit a Ticket",
    priority: "Priority",
    subject: "Subject",
    message: "Message",
    upload_files: "Upload Files",
    drag_drop: "Drag files here or click to browse",
    max_size: "Max size 5MB each, supported: images/text/pdf",
    submit_btn: "Submit Ticket",
    ticket_id: "Ticket ID",
    community: "Community",
    join_community: "Join Our Community",
    social_links: "Social Links",
    copy_link: "Copy Link",
    copied: "Copied!",
    visit: "Visit",
    return_exchange: "Return & Exchange",
    return: "Return",
    exchange: "Exchange",
    sales_return: "Sales Return",
    return_history: "Return History",
    return_products: "Return Products",
    sales_exchange: "Sales Exchange",
    exchange_history: "Exchange History",
    exchange_products: "Exchange Products",
    billing_summary: "Billing Summary",
    retail_return: "Retail Return",
    party_return: "Party Return",
    total_deduction: "Total Deduction",
    total_returnable: "Total Returnable",
    return_qty: "Return Qty",
    return_value: "Return Value",
    exchange_qty: "Exchange Qty",
    exchange_value: "Exchange Value",
    payable_amount: "Payable Amount",
    submit_exchange: "Submit Exchange",
    submit_return: "Submit Return"
  },
  bn: {
    dashboard: 'ড্যাশবোর্ড',
    sales: 'বিক্রয়',
    delivery: 'ডেলিভারি',
    marketing: 'মার্কেটিং',
    purchase: 'ক্রয়',
    expenses: 'খরচ',
    stock: 'ইনভেন্টরি',
    parties: 'পার্টি',
    reports: 'রিপোর্ট',
    settings: 'সেটিংস',
    home: 'হোম',
    promo_sms: 'প্রোমো ও এসএমএস',
    courier: 'কুরিয়ার',
    inventory: 'ইনভেন্টরি',
    todays_overview: "আজকের ওভারভিউ",
    total_sales: "মোট বিক্রয়",
    total_expense: "মোট খরচ",
    net_profit: "নিট লাভ",
    pending_delivery: "পেন্ডিং ডেলিভারি",
    new_sale: "নতুন বিক্রয়",
    bulk_sms: "বাল্ক SMS",
    search_product: "পণ্য খুঁজুন...",
    bill: "বিল",
    items: "আইটেম",
    total: "মোট",
    checkout: "চেকআউট",
    finalize_sale: "বিক্রয় সম্পন্ন করুন",
    customer: "গ্রাহক",
    walk_in: "সাধারণ গ্রাহক",
    coupon_code: "কুপন কোড",
    apply: "প্রয়োগ করুন",
    store_pickup: "দোকান থেকে সংগ্রহ",
    courier_delivery: "কুরিয়ার ডেলিভারি",
    payment_method: "পেমেন্ট মেথড",
    subtotal: "সাবটোটাল",
    discount: "ডিসকাউন্ট",
    delivery_fee: "ডেলিভারি ফি",
    total_payable: "মোট প্রদেয়",
    paid_amount: "জমা দিয়েছেন",
    due: "বাকি",
    confirm_sale: "বিক্রয় নিশ্চিত করুন",
    delivery_tracking: "ডেলিভারি ট্র্যাকিং",
    order_id: "অর্ডার আইডি",
    tracking: "ট্র্যাকিং",
    status: "স্ট্যাটাস",
    coupon_management: "কুপন ম্যানেজমেন্ট",
    bulk_sms_marketing: "বাল্ক SMS মার্কেটিং",
    send_broadcast: "ব্রডকাস্ট পাঠান",
    sales_report_invoice: "বিক্রয় রিপোর্ট ও ইনভয়েস",
    date: "তারিখ",
    amount: "পরিমাণ",
    method: "মাধ্যম",
    action: "অ্যাকশন",
    invoice: "ইনভয়েস",
    add_expense: "খরচ যোগ করুন",
    note: "বিবরণ",
    category: "ক্যাটাগরি",
    product_stock: "পণ্যের স্টক",
    add_product: "পণ্য যোগ করুন",
    name: "নাম",
    cost: "ক্রয় মূল্য",
    price: "খুচরা মূল্য (MRP)",
    party_list: "পার্টি তালিকা",
    add_party: "পার্টি যোগ করুন",
    suppliers: "সরবরাহকারী",
    purchase_stock: "পণ্য ক্রয়",
    supplier: "সরবরাহকারী",
    product: "পণ্য",
    qty: "পরিমাণ",
    unit_cost: "ইউনিট খরচ",
    confirm_purchase: "ক্রয় নিশ্চিত করুন",
    shop_config: "দোকান কনফিগারেশন",
    shop_name: "দোকানের নাম",
    currency: "মুদ্রা",
    save_changes: "পরিবর্তন সংরক্ষণ করুন",
    log_out: "লগ আউট",
    owner: "দোকান মালিক",
    business_suite: "বিজনেস স্যুট",
    pending: "পেন্ডিং",
    shipped: "শিপড",
    delivered: "ডেলিভারড",
    type_message: "আপনার বার্তা লিখুন...",
    add: "যোগ করুন",
    close: "বন্ধ করুন",
    print_invoice: "প্রিন্ট ইনভয়েস",
    bill_to: "বিল টু",
    via: "মাধ্যম",
    history: "হিস্ট্রি",
    stock_log: "স্টক লগ",
    low_stock: "লো স্টক",
    adjustment: "সমন্বয়",
    purchase_history: "ক্রয় ইতিহাস",
    total_spent: "মোট খরচ",
    view_history: "হিস্ট্রি দেখুন",
    inv_dashboard: "ইনভেন্টরি ড্যাশবোর্ড",
    product_list: "পণ্য তালিকা",
    stock_report: "স্টক রিপোর্ট",
    detailed_report: "বিস্তারিত রিপোর্ট",
    stock_ledger: "স্টক লেজার",
    stock_transfer: "স্টক ট্রান্সফার",
    serial_manage: "সিরিয়াল ম্যানেজ",
    total_items: "মোট আইটেম",
    stock_value_cost: "স্টক মান (ক্রয়)",
    stock_value_sales: "স্টক মান (বিক্রয়)",
    est_profit: "সম্ভাব্য লাভ",
    transfer: "ট্রান্সফার",
    from: "থেকে",
    to: "প্রতি",
    serial_no: "সিরিয়াল নং",
    add_serial: "সিরিয়াল যোগ",
    available: "মজুদ",
    sold: "বিক্রিত",
    brand: "ব্র্যান্ড",
    units: "ইউনিট",
    size: "সাইজ",
    color: "রঙ",
    wholesale_price: "পাইকারি মূল্য",
    vat: "ভ্যাট",
    is_vat: "ভ্যাট প্রযোজ্য?",
    alert_qty: "স্টক অ্যালার্ট পরিমাণ",
    stock_in: "স্টক ইন",
    warranty: "ওয়ারেন্টি",
    mfg_date: "উৎপাদন তারিখ",
    exp_date: "মেয়াদ উত্তীর্ণের তারিখ",
    upload_photo: "ছবি আপলোড",
    variations: "ভেরিয়েশন",
    sku: "SKU",
    create_invoice: "ইনভয়েস তৈরি",
    sold_history: "বিক্রয় ইতিহাস",
    sold_products: "বিক্রিত পণ্য",
    customer_history: "গ্রাহক ইতিহাস",
    retail_sale: "খুচরা বিক্রয়",
    wholesale: "পাইকারি",
    phone_number: "ফোন নম্বর",
    customer_name: "গ্রাহকের নাম",
    address: "ঠিকানা",
    total_qty: "মোট পরিমাণ",
    additional_expense: "অতিরিক্ত খরচ",
    total_discount: "মোট ডিসকাউন্ট",
    change_amount: "ফেরত পরিমাণ",
    remarks: "মন্তব্য",
    service_staff: "সার্ভিস স্টাফ",
    sl: "SL",
    invoice_no: "ইনভয়েস নং",
    type: "ধরন",
    quantity: "পরিমাণ",
    store_name: "দোকানের নাম",
    faq: "জিজ্ঞাসিত প্রশ্ন",
    help: "হেল্প",
    faq_title: "সচরাচর জিজ্ঞাসিত প্রশ্নাবলী",
    faq_subtitle: "সাধারণ প্রশ্নের উত্তর খুঁজুন",
    q1: "আমি কিভাবে আমার পাসওয়ার্ড রিসেট করব?",
    q2: "আপনারা কি ফ্রি ট্রায়াল দেন?",
    q3: "আমি কি পরে সাবস্ক্রিপশন প্ল্যান পরিবর্তন করতে পারব?",
    q4: "আমার ডেটা কি সুরক্ষিত?",
    q5: "আপনারা কি কাস্টমার সাপোর্ট দেন?",
    support: "হেল্প ও সাপোর্ট",
    ticket_list: "টিকেট লিস্ট",
    create_ticket: "টিকেট তৈরি করুন",
    hotline: "হটলাইন",
    submit_ticket: "টিকেট জমা দিন",
    priority: "অগ্রাধিকার",
    subject: "বিষয়",
    message: "বার্তা",
    upload_files: "ফাইল আপলোড",
    drag_drop: "ফাইল এখানে টেনে আনুন বা ব্রাউজ করুন",
    max_size: "সর্বোচ্চ ৫ মেগাবাইট, ইমেজ/টেক্সট/পিডিএফ",
    submit_btn: "টিকেট জমা দিন",
    ticket_id: "টিকেট আইডি",
    community: "কমিউনিটি",
    join_community: "কমিউনিটিতে যোগ দিন",
    social_links: "সোশ্যাল লিংক",
    copy_link: "লিংক কপি",
    copied: "কপি হয়েছে!",
    visit: "ভিজিট",
    return_exchange: "রিটার্ন ও এক্সচেঞ্জ",
    return: "রিটার্ন",
    exchange: "এক্সচেঞ্জ",
    sales_return: "সেলস রিটার্ন",
    return_history: "রিটার্ন হিস্ট্রি",
    return_products: "রিটার্ন পণ্য",
    sales_exchange: "সেলস এক্সচেঞ্জ",
    exchange_history: "এক্সচেঞ্জ হিস্ট্রি",
    exchange_products: "এক্সচেঞ্জ পণ্য",
    billing_summary: "বুকিং সারসংক্ষেপ",
    retail_return: "খুচরা রিটার্ন",
    party_return: "পার্টি রিটার্ন",
    total_deduction: "মোট কর্তন",
    total_returnable: "মোট ফেরতযোগ্য",
    return_qty: "রিটার্ন পরিমাণ",
    return_value: "রিটার্ন মূল্য",
    exchange_qty: "এক্সচেঞ্জ পরিমাণ",
    exchange_value: "এক্সচেঞ্জ মূল্য",
    payable_amount: "প্রদেয় পরিমাণ",
    submit_exchange: "এক্সচেঞ্জ নিশ্চিত করুন",
    submit_return: "রিটার্ন নিশ্চিত করুন"
  }
};
